/**
 * build-ui.mjs — esbuild pipeline for the conductor dashboard React app.
 *
 * Input:  src/ui/index.tsx  (+ all imports under src/ui/)
 * Output: src/ui-bundle.ts  (generated TypeScript that exports htmlDashboard(): string)
 *
 * The generated file is excluded from biome lint and committed to .gitignore.
 * It is rebuilt automatically by `npm run build` (node build-ui.mjs && tsc).
 */

import * as esbuild from "esbuild";
import { writeFileSync } from "node:fs";

const result = await esbuild.build({
  entryPoints: ["src/ui/index.tsx"],
  bundle: true,
  format: "iife",
  target: ["es2020"],
  jsx: "automatic",
  jsxImportSource: "react",
  minify: true,
  write: false,
  // esbuild requires outdir even when write:false
  outdir: "out",
  define: { "process.env.NODE_ENV": '"production"' },
  // CSS imported via `import "./styles.css"` in index.tsx will produce a separate output file
  loader: { ".css": "css" },
});

if (result.errors.length > 0) {
  for (const err of result.errors) console.error(err.text);
  process.exit(1);
}

const jsFile = result.outputFiles.find((f) => f.path.endsWith(".js"));
const cssFile = result.outputFiles.find((f) => f.path.endsWith(".css"));

if (!jsFile) {
  console.error("esbuild produced no JS output");
  process.exit(1);
}

const html = [
  "<!DOCTYPE html><html lang=\"en\"><head>",
  "<meta charset=\"UTF-8\">",
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">",
  "<title>conductor</title>",
  "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">",
  "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>",
  "<link href=\"https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,300..600;1,14..32,300..600&family=JetBrains+Mono:wght@400;500&display=swap\" rel=\"stylesheet\">",
  cssFile ? `<style>${cssFile.text}</style>` : "",
  "</head><body><div id=\"root\"></div>",
  `<script>${jsFile.text}</script>`,
  "</body></html>",
].join("");

// JSON.stringify produces a valid TS string literal with all chars escaped
const escaped = JSON.stringify(html);
const output = `// @generated by build-ui.mjs — do not edit manually
export function htmlDashboard(): string { return ${escaped}; }
`;

writeFileSync("src/ui-bundle.ts", output, "utf8");
const kb = (html.length / 1024).toFixed(1);
console.log(`\u2714 src/ui-bundle.ts generated (${kb} KB)`);
